### ISSUE TITLE
Latest commit on main branch is not building

### ISSUE THREAD

**Issue by s3rgiux** [MORAI-Autonomous/MORAI-ROS2_morai_msgs#10]
while trying to build Autoware i realize that this module was failing, seems that is missing a name field for the Service
**srv/ElevatorStatusSrv.srv**, the file has the next elements however the field std_msgs/Empty needs a name or being commented :

**std_msgs/Empty**
---
std_msgs/Header header

float64[] time_stamp

int64[] ev_id

int64[] door_status

int64[] source_floor
int64[] target_floor
int64[] ev_floor

float64[] ev_velocity

solved temporary adding a name for the type **std_msgs/Empty**

**std_msgs/Empty signal**

**Comment by Owen-Liuyuxuan** [comment]
https://github.com/MORAI-Autonomous/MORAI-ROS2_morai_msgs/pull/9#issuecomment-2295856122

We have the same report here. I would love to see a fix soon.

**Comment by cjmodi306** [comment]
@Owen-Liuyuxuan thanks for the quick fix. Was currently dealing with the same issue.

**Comment by hwjung-morai** [comment]
#11 The pull request has been merged. Closing issue.
